name: 'Add to Milestone'
description: 'Add PR to a milestone'
author: 'andrefcdias'
inputs:
  milestone: # change this
    required: true
    description: 'Milestone name'

runs:
  using: 'node12'
  main: 'dist/index.js'
