name: 'Add to Milestone'
description: 'Add PR to a milestone'
author: 'andrefcdias'

branding:
  icon: tag
  color: blue

runs:
  using: 'node12'
  main: 'dist/index.js'

inputs:
  repo-token:
    required: true
    description: 'Github token.'
  milestone:
    required: true
    description: 'Name of the milestone or glob pattern'
  use-expression:
    required: false
    default: false
    description: 'Trigger pattern matching using globs with https://github.com/isaacs/minimatch'
  allow-inactive:
    required: false
    default: false
    description: 'Control if milestones past their due date should be included'
  users-file-path:
    required: false
    description: 'Name of the file that contains users for whom the action will trigger for'
